name: Build & Push Microgateway image

on:
  workflow_call:
    inputs:
      docker-repository:
        required: true
        type: string
      aws-role-session-name:
        required: true
        type: string
      aws-region:
        required: true
        type: string
    secrets:
      aws-role-to-assume:
        required: true
      github-token:
        required: true
      docker-registry:
        required: true

permissions:
  id-token: write
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"
          token: ${{ secrets.github-token }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.aws-role-to-assume }}
          role-session-name: ${{ inputs.aws-role-session-name }}
          aws-region: ${{ inputs.aws-region }}
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        run: |
          echo ${GITHUB_REF_NAME}
          export BRANCH_TAG=$(echo "${GITHUB_REF_NAME}" | sed -E 's/([^0-9a-zA-Z]+)/-/g' | awk '{print tolower($0)}')

          docker build -t $ECR_REPOSITORY .

          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG
          docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG-${GITHUB_SHA::7}

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG-${GITHUB_SHA::7}
        env:
          ECR_REGISTRY: ${{ secrets.docker-registry }}
          ECR_REPOSITORY: ${{ inputs.docker-repository }}
