name: Test plugin

on:
  workflow_call:
    inputs:
      collection-path:
        required: true
        type: string
      environment-path:
        required: true
        type: string

env:
  REGISTRY: ghcr.io

permissions:
  id-token: write
  contents: read # This is required for actions/checkout
  packages: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run integration tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Start KrakenD Gateway
        run: make run-ci

      - name: Ping Gateway
        run: |
          curl -v "http://localhost:8080/__health"

      - name: Run integration tests
        uses: matt-ball/newman-action@master
        with:
          collection: ${{ inputs.collection-path }}
          environment: ${{ inputs.environment-path }}
