name: Build & push KidsLoop krakend images

on:
  push:
    paths:
      - "docker-versions.sh"
    branches:
      - "*"

env:
  REGISTRY: ghcr.io

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  read-versions:
    runs-on: ubuntu-latest
    outputs:
      golang-version: ${{ steps.versions.outputs.golang-version }}
      krakend-version: ${{ steps.versions.outputs.krakend-version }}
      kl-builder-version: ${{ steps.versions.outputs.kl-builder-version }}
      kl-krakend-version: ${{ steps.versions.outputs.kl-krakend-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read versions
        id: versions
        run: |
          source ./docker-versions.sh
          echo "::set-output name=golang-version::${GOLANG_VERSION}"
          echo "::set-output name=krakend-version::${KRAKEND_VERSION}"
          echo "::set-output name=kl-builder-version::${KL_BUILDER_VERSION}"
          echo "::set-output name=kl-krakend-version::${KL_KRAKEND_VERSION}"

  build-and-push-builder-image:
    needs: read-versions
    runs-on: ubuntu-latest
    name: Build & push kl-builder image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/kl-krakend-builder
          tags: |
            type=semver,pattern={{version}},value=${{ needs.read-versions.outputs.kl-builder-version }}

      - name: Echo tags
        run: |
          echo "${{ steps.meta.outputs.tags }}"
          echo "${{ steps.meta.outputs.labels }}"

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./Dockerfile.builder
          build-args: |
            IMAGE_VERSION=${{ needs.read-versions.outputs.golang-version }}

  build-and-push-krakend-image:
    runs-on: ubuntu-latest
    needs: read-versions
    name: Build & push kl-krakend image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/kl-krakend
          tags: |
            type=semver,pattern={{version}},value=${{ needs.read-versions.outputs.kl-krakend-version }}

      - name: Echo tags
        run: |
          echo "${{ steps.meta.outputs.tags }}"
          echo "${{ steps.meta.outputs.labels }}"

      - name: Build and push docker image
        uses: docker/build-push-action@v2
        id: build-push-krakend
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: ./Dockerfile.krakend
          build-args: |
            IMAGE_VERSION=${{ needs.read-versions.outputs.krakend-version }}
