name: Sync central managed configuration

on:
  push:
    branches:
      - main

jobs:
  sync:
    name: "Sync centrally managed configuration with microgateways"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microgateway: ["KL-Engineering/factory-shared-microgateway"]

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout central repository
        uses: actions/checkout@v3
        with:
          path: "central"
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.microgateway }}
          path: "target"
          token: ${{ secrets.GH_PAT }}
      - name: Merge configuration
        id: merge-config
        run: |
          rsync -av central/config/ target/config

          git config --global user.name 'microgateway-sync'
          git config --global user.email 'github-action@noreply.github.com'

          GH_SHA=${GITHUB_REF##*/}/${GITHUB_SHA::7}
          BRANCH_NAME=microgateway-sync/$GH_SHA

          cd target

          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "chore(microgateway-sync): auto updated central configuration $GH_SHA" && git push --set-upstream origin $BRANCH_NAME || echo "No changes to commit"
          echo "::set-output name=pr-branch-name::$BRANCH_NAME"
      - name: Create pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            const splitGateway = '${{ matrix.microgateway }}'.split('/');
            const owner = splitGateway[0];
            const repo = splitGateway[1];
            const head = '${{ steps.merge-config.outputs.pr-branch-name }}';
            const splitHead = head.split('/');
            const result = await github.rest.pulls.create({
              title: '[Sync] Auto-sync of centrally managed gateway configuration',
              owner,
              repo,
              head,
              base: 'main',
              body: [
                ':bangbang: :robot: This PR is auto-generated by [actions/github-script](https://github.com/actions/github-script)',
                '',
                'Changes have been made to the up-stream [centrally managed configuration](https://github.com/KL-Engineering/central-microgateway-configuration)',
                '',
                '|         | Branch          | SHA             |',
                '| ------- | :-------------: | :-------------: |',
                '| Details | `' + `${splitHead[1]}` + '` | `' + `${splitHead[2]}` + '` |',
                '',
                'Please review and merge this in as soon as possible.'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['automated pr', 'microgateway-sync']
            });
