name: Sync central managed artefacts

on:
  release:
    types: [published, prereleased]

jobs:
  read-sync-targets:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - id: set-matrix
        name: Read from microgateway configuration
        run: |
          JSON=$(jq -n '[ inputs ] | add' microgateways.json managed-repositories.json)
          JSON="${JSON//'%'/'%25'}"
          JSON="${JSON//$'\n'/'%0A'}"
          JSON="${JSON//$'\r'/'%0D'}"

          echo "::set-output name=matrix::${JSON}"

  read-versions:
    runs-on: ubuntu-latest
    outputs:
      golang-version: ${{ steps.versions.outputs.golang-version }}
      krakend-version: ${{ steps.versions.outputs.krakend-version }}
      kl-builder-version: ${{ steps.versions.outputs.kl-builder-version }}
      kl-krakend-version: ${{ steps.versions.outputs.kl-krakend-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Read versions
        id: versions
        run: |
          source ./docker-versions.sh
          echo "::set-output name=golang-version::${GOLANG_VERSION}"
          echo "::set-output name=krakend-version::${KRAKEND_VERSION}"
          echo "::set-output name=kl-builder-version::${KL_BUILDER_VERSION}"
          echo "::set-output name=kl-krakend-version::${KL_KRAKEND_VERSION}"

  sync-configuration:
    name: "Sync centrally managed configuration with microgateways"
    needs: read-sync-targets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        microgateway: ${{ fromJson(needs.read-sync-targets.outputs.matrix) }}

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout central repository
        uses: actions/checkout@v3
        with:
          path: "central"
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.microgateway }}
          path: "target"
          token: ${{ secrets.GATEWAY_CONFIG_SYNC_BOT }}
      - name: Merge configuration
        id: merge-config
        run: |
          rsync -av central/config/ target/config

          git config --global user.name 'microgateway-sync'
          git config --global user.email 'github-action@noreply.github.com'

          GH_SHA=${GITHUB_REF##*/}/${GITHUB_SHA::7}
          BRANCH_NAME=microgateway-sync/$GH_SHA

          cd target

          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "chore(microgateway-sync): auto updated central configuration $GH_SHA" && git push --set-upstream origin $BRANCH_NAME || touch no-commit

          if [ -f "no-commit" ]; then
            echo "::set-output name=commit-status::no-commit"
          else
            echo "::set-output name=pr-branch-name::$BRANCH_NAME"
          fi
      - name: Create pull request
        uses: actions/github-script@v6
        if: steps.merge-config.outputs.commit-status != 'no-commit'
        with:
          github-token: ${{ secrets.GATEWAY_CONFIG_SYNC_BOT }}
          script: |
            const splitGateway = '${{ matrix.microgateway }}'.split('/');
            const owner = splitGateway[0];
            const repo = splitGateway[1];
            const head = '${{ steps.merge-config.outputs.pr-branch-name }}';
            const splitHead = head.split('/');
            const result = await github.rest.pulls.create({
              title: '[Sync] Auto-sync of centrally managed gateway configuration',
              owner,
              repo,
              head,
              base: 'main',
              body: [
                ':bangbang: :robot: This PR is auto-generated by [actions/github-script](https://github.com/actions/github-script)',
                '',
                'Changes have been made to the up-stream [centrally managed configuration](https://github.com/KL-Engineering/central-microgateway-configuration)',
                '',
                '|         | Branch          | SHA             |',
                '| ------- | :-------------: | :-------------: |',
                '| Details | `' + `${splitHead[1]}` + '` | `' + `${splitHead[2]}` + '` |',
                '',
                'Please review and merge this in as soon as possible.'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['automated pr', 'microgateway-sync']
            });

  sync-docker-images:
    name: "Sync centrally managed dockerfiles with microgateways"
    runs-on: ubuntu-latest
    needs: [read-versions, read-sync-targets]
    strategy:
      matrix:
        microgateway: ${{ fromJson(needs.read-sync-targets.outputs.matrix) }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ matrix.microgateway }}
          token: ${{ secrets.GATEWAY_CONFIG_SYNC_BOT }}
      - name: Update Dockerfile
        id: update-dockerfile
        run: |

          sed -i "s/kl-krakend-builder:[0-9.]*/kl-krakend-builder:${{ needs.read-versions.outputs.kl-builder-version }}/g" Dockerfile
          sed -i "s/kl-krakend:[0-9.]*/kl-krakend:${{ needs.read-versions.outputs.kl-krakend-version }}/g" Dockerfile
          sed -i "s/kl-krakend:[0-9.]*/kl-krakend:${{ needs.read-versions.outputs.kl-krakend-version }}/g" Dockerfile.validate

          git config --global user.name 'microgateway-sync'
          git config --global user.email 'github-action@noreply.github.com'

          BRANCH_NAME=microgateway-sync/krakend-${{ needs.read-versions.outputs.kl-krakend-version }}-builder-${{ needs.read-versions.outputs.kl-builder-version }}

          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "chore(microgateway-sync): auto updated dockerfiles with new base images" && git push --set-upstream origin $BRANCH_NAME || touch no-commit

          if [ -f "no-commit" ]; then
            echo "::set-output name=commit-status::no-commit"
          else
            echo "::set-output name=pr-branch-name::$BRANCH_NAME"
          fi

      - name: Create pull request
        uses: actions/github-script@v6
        if: steps.update-dockerfile.outputs.commit-status != 'no-commit'
        with:
          github-token: ${{ secrets.GATEWAY_CONFIG_SYNC_BOT }}
          script: |
            const splitGateway = '${{ matrix.microgateway }}'.split('/');
            const owner = splitGateway[0];
            const repo = splitGateway[1];
            const head = '${{ steps.update-dockerfile.outputs.pr-branch-name }}';
            const splitHead = head.split('/');
            const result = await github.rest.pulls.create({
              title: '[Sync] Auto-sync of centrally managed gateway configuration',
              owner,
              repo,
              head,
              base: 'main',
              body: [
                ':bangbang: :robot: This PR is auto-generated by [actions/github-script](https://github.com/actions/github-script)',
                '',
                'Changes have been made to the up-stream [centrally managed configuration](https://github.com/KL-Engineering/central-microgateway-configuration)',
                '',
                '|         | Release          |',
                '| ------- | :-------------: |',
                '| Details | ` KL-Engineering/central-microgateway-configuration/' + '${{ github.ref_name }}' + '` |',
                '',
                'Please review and merge this in as soon as possible.'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['automated pr', 'microgateway-sync']
            });
