name: Validate Microgateway Configuration

on:
  workflow_call:
    secrets:
      github-repo-token:
        required: true
      github-package-token:
        required: true

permissions:
  id-token: write
  contents: read # This is required for actions/checkout
  packages: read

jobs:
  read-configuration:
    runs-on: ubuntu-latest
    outputs:
      regions-matrix: ${{ steps.set-matrix.outputs.regions-matrix }}
      environments-matrix: ${{ steps.set-matrix.outputs.environments-matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: "KL-Engineering/central-microgateway-configuration"
          token: ${{ secrets.github-repo-token }}

      - id: set-matrix
        name: Read supported regions and environments
        run: |
          REGIONS_JSON=$(cat ./regions.json)
          REGIONS_JSON="${REGIONS_JSON//'%'/'%25'}"
          REGIONS_JSON="${REGIONS_JSON//$'\n'/'%0A'}"
          REGIONS_JSON="${REGIONS_JSON//$'\r'/'%0D'}"
          echo "::set-output name=regions-matrix::${REGIONS_JSON}"

          ENVIRONMENTS_JSON=$(cat ./environments.json)
          ENVIRONMENTS_JSON="${ENVIRONMENTS_JSON//'%'/'%25'}"
          ENVIRONMENTS_JSON="${ENVIRONMENTS_JSON//$'\n'/'%0A'}"
          ENVIRONMENTS_JSON="${ENVIRONMENTS_JSON//$'\r'/'%0D'}"
          echo "::set-output name=environments-matrix::${ENVIRONMENTS_JSON}"

  test-configuration:
    runs-on: ubuntu-latest
    needs: read-configuration
    strategy:
      matrix:
        regions: ${{ fromJson(needs.read-configuration.outputs.regions-matrix) }}
        environment: ${{ fromJson(needs.read-configuration.outputs.environments-matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "recursive"
          token: ${{ secrets.github-repo-token }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.github-package-token }}

      - name: Build docker image
        run: docker build -t validate -f Dockerfile.validate .

      - name: Run validation
        env:
          REGION: ${{ matrix.regions }}
          ENVIRONMENT: ${{ matrix.environment }}
        run: docker run -e REGION=$REGION -e ENVIRONMENT=$ENVIRONMENT validate
